# Generated by Django 5.2.1 on 2025-05-17 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_tugas', models.FileField(upload_to='tugas/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hash_tugas', models.CharField(max_length=64)),
                ('previous_hash', models.CharField(max_length=64)),
                ('grades_tugas', models.TextField(blank=True, null=True)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_terenkripsi', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('signature', models.TextField()),
                ('hash_nilai', models.CharField(max_length=64)),
                ('nilai_asli', models.IntegerField(blank=True, null=True)),
                ('tugas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grades.tugas')),
            ],
        ),
    ]
